;loggingの設定

[loggers]
;logging.getLogger(logger name)のlogger nameに指定する名前
;root は、 mainで実行した時に自動的に取得できる名前
;outputLoggingのように独自のロガー名を追加できる
keys=root, DRLLogging,DRLTrainer,DRLRoot,DRLAgent,DRLTrader,DRLTraderServer,DRLPortfolio

;ハンドラの設定(customStreamHandlerは任意で付けた名前)
[handlers]
keys=customStreamHandler

;フォーマットの設定(customFormatは任意で付けた名前)
[formatters]
keys=customFormat

;---詳細の設定
;logger_[loggers の key 名] とし、詳細を記述していく
[logger_root]
level=DEBUG
handlers=customStreamHandler

[logger_DRLRoot]
level=DEBUG
handlers=customStreamHandler
qualname=DRLRoot
propagate=0

[logger_DRLLogging]
level=INFO
handlers=customStreamHandler
qualname=DRLLogging
propagate=0

[logger_DRLAgent]
level=DEBUG
handlers=customStreamHandler
qualname=DRLAgent
propagate=0

[logger_DRLTrainer]
level=DEBUG
handlers=customStreamHandler
qualname=DRLTrainer
propagate=0

[logger_DRLTrader]
level=DEBUG
handlers=customStreamHandler
qualname=DRLTrader
propagate=0

[logger_DRLTraderServer]
level=DEBUG
handlers=customStreamHandler
qualname=DRLTraderServer
propagate=0

[logger_DRLPortfolio]
level=DEBUG
handlers=customStreamHandler
qualname=DRLPortfolio
propagate=0

;---詳細の設定に追加するためのオプション
;handler_[handlers の 名前]
[handler_customStreamHandler]
class=StreamHandler
level=DEBUG
formatter=customFormat
args=(sys.stderr,)

;---formatter_[formatter の 名前]
[formatter_customFormat]
format=%(asctime)s %(name)-12s %(levelname)-8s %(message)s