# LocalとColaboの両方で共通して使う定数
# [DEFAULT]
[COMMOM]
# 時間足のリスト。時間足×通貨ペアの組み合わせで訓練する
TRAIN_PERIOD_LIST = ['H1']
# 通貨ペアのリスト。時間足×通貨ペアの組み合わせで訓練する
TRAIN_SYMBOL_LIST = ['EURUSD','USDJPY']

# スプレッドは、通貨ペアに応じて変更する。
MARGIN_DICT = {'EURUSD':0.02,'USDJPY':0.02,'EURJPY':0.03,
	'GBPUSD':0.02,'EURGBP':0.02,'GBPJPY':0.04,'AUDUSD':0.02,
	'EURAUD':0.02,'AUDJPY':0.04,'GBPAUD':0.06,'USDCHF':0.02,
	'EURCHF':0.02,'CHFJPY':0.02,'GBPCHF':0.04,'AUDCHF':0.04,
	'USDCAD':0.02,'EURCAD':0.04,'CADJPY':0.04,'GBPCAD':0.06,
	'AUDCAD':0.02,'CADCHF':0.04,'NZDUSD':0.02,'EURNZD':0.04,
	'NZDJPY':0.02,'GBPNZD':0.06,'AUDNZD':0.04,'NZDCHF':0.04,
	'NZDCAD':0.04,'USDZAR':0.06}

# MT5のPeriod(TimeFrame)と、Pandas rolling のfreqを対応付ける辞書
PERIOD_FREQ_DICT = {"M1":"1min","M2":"2min","M3":"3min","M4":"4min","M5":"5min","M6":"6min"
	,"M10":"10min","M12":"12min","M15":"15min","M20":"20min","M30":"30min","H1":"1h"
	,"H2":"2h","H3":"3h","H4":"4h","H6":"6h","H8":"8h","H12":"12h"
	,"D1":"D","W1":"W","MN1":"MS"}

# in Environment.PriceData.AddSMAStdev()
LONG_PERIOD = 31
SHORT_PERIOD = 13

# Digit別の通貨ペア新しい通貨ペアを学習させるときはここに登録する
SYMBOL_5DIGITS = ['EURUSD','GBPUSD','EURGBP','AUDUSD','EURAUD'
	,'GBPAUD','USDCHF','EURCHF','GBPCHF','AUDCHF','USDCAD'
	,'EURCAD','GBPCAD','AUDCAD','CADCHF','NZDUSD','EURNZD',
	'GBPNZD','AUDNZD','NZDCHF','NZDCAD']
SYMBOL_3DIGITS = ['USDJPY','EURJPY','GBPJPY','AUDJPY','CHFJPY',
	'CADJPY','NZDJPY']
SYMBOL_4DIGITS = ['USDZAR']

# Digit別の倍率を定義する
DIGIT_MAGNIFICATION = {'SYMBOL_5DIGITS':100,'SYMBOL_4DIGITS':10
	,'SYMBOL_3DIGITS':1}

# TICKVOLの平均を計算する期間
TICKVOL_PERIOD = 31
TICKVOL_MAGNIFICATION = 100000

# T/PとL/Cをランダムに取得する際の、範囲とステップを指定する
TP_LC_MIN_LEVEL = 300
TP_LC_MAX_LEVEL = 3000
TP_LC_STEP = 50

BACKTEST_RESULT_ALL_FILE_NAME = BacktestResult_All.csv
BACKTEST_ALL_FILE_NAME = BacktestResultPortfolio_All.csv
MODEL_PORTFOLIO_FILE_NAME = ModelPortfolio.ini

# LINE Notifyでメッセージを送信するためのトークン
LINE_NOTIFY_TOKEN = 8aWFL1Ka3by4uSF29cywkElNB5qjy9rb0gPwv2tLKvd
# LINE Messaging APIを利用するためのトークン
LINE_MESSAGING_API_TOKEN = o4JFzpgQ5tctbpw5kjlVtdoll2U6GjntCCkqZGppnpYVeNZfcDtFV7UQWbF6AbgwDJKs+ZVY9CRGe8LKh++UHGN3gfMffSzHxmLpvTnBJBZmHGE2Mw6mBnoYl1lroiXJeYfxzY9P+U/nXa5XxozgvAdB04t89/1O/w1cDnyilFU=

# TradeSystemの名称
TRADE_SYSTEM = COMMON

# Colaboで使用する定数
[COLABO]
# Logging.ini file path
LOGGING_INIFILE_PATH = ./drive/MyDrive/Colab Notebooks/00_Common/Logging.ini

# in Environment.PriceData.__init__()
# PRICEDATA_PATH_COLABO = ./drive/MyDrive/Colab Notebooks/02_DRLTradingSystem2020/PriceData/
PRICEDATA_PATH_REAL = ./drive/MyDrive/Colab Notebooks/02_DRLTradingSystem2020/PriceData/
PRICEDATA_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/02_DRLTradingSystem2020/Demo/PriceData/

# TRAIN_MODEL_PATH
TRAIN_MODEL_PATH_REAL = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Train/
TRAIN_MODEL_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/00_Common/Demo/Model/Train/

# in Trainer
# TMP_TRAIN_MODEL_PARTH_COLABO = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Train/Tmp/
TMP_TRAIN_MODEL_PATH_REAL = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Train/Tmp/
TMP_TRAIN_MODEL_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/00_Common/Demo/Model/Train/Tmp/

# TRADE_MODEL_PATH_COLABO = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Trade/
TRADE_MODEL_PATH_REAL = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Trade/
TRADE_MODEL_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/00_Common/Demo/Model/Trade/

# TRADE_RESULT_PATH
TRADE_RESULT_PATH_REAL = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Trade/Result/
TRADE_RESULT_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/00_Common/Demo/Model/Trade/Result/
# TRAIN_RESULT_PATH
TRAIN_RESULT_PATH_REAL = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Train/Result/
TRAIN_RESULT_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/00_Common/Demo/Model/Train/Result/

# TMP_TRAIN_RESULT_PATH
TMP_TRAIN_RESULT_PATH_REAL = ./drive/MyDrive/Colab Notebooks/00_Common/Model/Train/Tmp/Result/
TMP_TRAIN_RESULT_PATH_DEMO = ./drive/MyDrive/Colab Notebooks/00_Common/Demo/Model/Train/Tmp/Reult/


[LOCAL]
# Logging.ini file path
LOGGING_INIFILE_PATH = D:\ColabNotebooks\00_Common\Logging.ini

# in Environment.PriceData.__init__()
PRICEDATA_PATH_REAL = D:\ColabNotebooks\00_Common\Real\PriceData\
PRICEDATA_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\PriceData\

# TICKDATA_PATH
TICKDATA_PATH_REAL = D:\ColabNotebooks\00_Common\Real\TickData\
TICKDATA_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\TickData\

# TRAIN_MODEL_PATH
TRAIN_MODEL_PATH_REAL = D:\ColabNotebooks\00_Common\Real\Model\Train\
TRAIN_MODEL_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Train\

# TRAIN_MODEL_PATH_VOID
TRAIN_MODEL_PATH_VOID_REAL = D:\ColabNotebooks\00_Common\Real\Model\Train\Void\
TRAIN_MODEL_PATH_VOID_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Train\Void\

# TMP_TRAIN_MODEL_PATH
TMP_TRAIN_MODEL_PATH_REAL = D:\ColabNotebooks\00_Common\Real\Model\Train\Tmp\
TMP_TRAIN_MODEL_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Train\Tmp\

# TRADE_MODEL_PATH
TRADE_MODEL_PATH_REAL = D:\ColabNotebooks\00_Common\Real\Model\Trade\
TRADE_MODEL_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Trade\

# TRADE_RESULT_PATH
TRADE_RESULT_PATH_REAL = D:\ColabNotebooks\00_Common\Real\Model\Trade\Result\
TRADE_RESULT_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Trade\Result\

# TRAIN_RESULT_PATH
TRAIN_RESULT_PATH_REAL = D:\ColabNotebooks\00_Common\Real\Model\Train\Result\
TRAIN_RESULT_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Train\Result\

# TRAIN_RESULT_PATH_VOID
TRAIN_RESULT_PATH_VOID_REAL = D:\ColabNotebooks\00_Common\Real\Model\Train\Result\Void\
TRAIN_RESULT_PATH_VOID_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Train\Result\Void\

# TMP_TRAIN_RESULT_PATH
TMP_TRAIN_RESULT_PATH_REAL = D:\ColabNotebooks\00_Common\Real\Model\Train\Tmp\Result\
TMP_TRAIN_RESULT_PATH_DEMO = D:\ColabNotebooks\00_Common\Demo\Model\Train\Tmp\Result\

# Settings on DRLTraderOnLocal
mt5_real_path = C:\Program Files\XM Trading MT5\terminal64.exe
mt5_demo_path = C:\Program Files\MetaTrader 5\terminal64.exe
# Settings on EnvironmentLocal
# mt5_path = C:\Program Files\XM Trading MT5\terminal64.exe

# askとbidの差。これ以上の時は取引をしない
REAL_SPREAD_LIMIT_LIST = {'EURUSD':0.02,'USDJPY':0.02,'EURJPY':0.04,
	'GBPUSD':0.03,'EURGBP':0.03,'GBPJPY':0.05,'AUDUSD':0.03,
	'EURAUD':0.03,'AUDJPY':0.04,'GBPAUD':0.06,'USDCHF':0.03,
	'EURCHF':0.03,'CHFJPY':0.05,'GBPCHF':0.06,'AUDCHF':0.04,
	'USDCAD':0.03,'EURCAD':0.04,'CADJPY':0.04,'GBPCAD':0.06,
	'AUDCAD':0.03,'CADCHF':0.04,'NZDUSD':0.03,'EURNZD':0.04,
	'NZDJPY':0.05,'GBPNZD':0.06,'AUDNZD':0.04,'NZDCHF':0.04,
	'NZDCAD':0.04,'USDZAR':0.06}

# RealSpreadが閾値以上の時にやり直す回数
MAX_RETRY_NUM = {'D1':720,'H12':360,'H8':240,'H6':180,'H4':120,
  'H1':30,'M30':15,'M5':3,'M1':2}

pricedata_path = D:\ColabNotebooks\00_Common\Real\PriceData\
pricedata_real_path = D:\ColabNotebooks\00_Common\Real\PriceData\
pricedata_demo_path = D:\ColabNotebooks\00_Common\Demo\PriceData\

TRADE_MODEL_REAL_PATH = D:\ColabNotebooks\00_Common\Real\Model\Trade\
TRADE_MODEL_DEMO_PATH = D:\ColabNotebooks\00_Common\Demo\Model\Trade\

# MT5のPeriod(Timeframe)と、Python Metatrader5 packageの定数名を対応付ける辞書
# Metatrader5 がimportされている必要がある
timrframe_dict = {"M1":mt5.TIMEFRAME_M1,"M2":mt5.TIMEFRAME_M2,"M3":mt5.TIMEFRAME_M3,
	"M4":mt5.TIMEFRAME_M4,"M5":mt5.TIMEFRAME_M5,"M6":mt5.TIMEFRAME_M6,"M10":mt5.TIMEFRAME_M10,
	"M12":mt5.TIMEFRAME_M12,"M15":mt5.TIMEFRAME_M15,"M20":mt5.TIMEFRAME_M20,
	"M30":mt5.TIMEFRAME_M30,"H1":mt5.TIMEFRAME_H1,"H2":mt5.TIMEFRAME_H2,"H3":mt5.TIMEFRAME_H3,
	"H4":mt5.TIMEFRAME_H4,"H6":mt5.TIMEFRAME_H6,"H8":mt5.TIMEFRAME_H8,"H12":mt5.TIMEFRAME_H12,
	"D1":mt5.TIMEFRAME_D1,"W1":mt5.TIMEFRAME_W1,"MN1":mt5.TIMEFRAME_MN1}

# Serverでロット計算を行うための期待週間成長率
# DemoとRealで成長率を分ける
GROWTH_RATE_DEMO = 0.1
GROWTH_RATE_REAL = 0.07

#NNModel別のモデル入出力素子数
[LOCAL_DQN2023]
INPUT_NUM = 75
HIDDEN_NUM = 75
OUTPUT_NUM = 6

[LOCAL_DUELNET]
INPUT_NUM = 76
HIDDEN_NUM = 76
OUTPUT_NUM = 6

[LOCAL_DUELNET2026]
INPUT_NUM = 76
HIDDEN_NUM = 76
OUTPUT_NUM = 6